"""empty message

Revision ID: 2e9e90946f2f
Revises: 
Create Date: 2019-05-26 19:32:20.153841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9e90946f2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('salt', sa.String(length=60), nullable=False),
    sa.Column('pubkey', sa.String(length=254), nullable=False),
    sa.Column('privkey', sa.String(length=254), nullable=False),
    sa.Column('pubkey_1', sa.String(length=254), nullable=False),
    sa.Column('privkey_1', sa.String(length=254), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.create_table('Joke',
    sa.Column('joke_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('solidity_address', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('joke_id')
    )
    op.create_table('Likes',
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.Column('Joke_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Joke_id'], ['Joke.joke_id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['User.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Likes')
    op.drop_table('Joke')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
